#zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

# custom
source ~/.bash_profile
source ~/.dotfiles/zsh/vi.zsh
source ~/.dotfiles/zsh/env.zsh
source ~/.venvs/myenv/bin/activate
eval "$(fnm env --use-on-cd)" #node #source $(brew --prefix nvm)/nvm.sh
precmd() {
    source ~/.dotfiles/zsh/aliases.zsh
}

# HSTR configuration - add this to ~/.zshrc
alias hh=hstr                    # hh to be alias for hstr
setopt histignorespace           # skip cmds w/ leading space from history
export HSTR_CONFIG=hicolor       # get more colors
#bindkey -s "\C-r" "\C-a hstr -- \C-j"     # bind hstr to Ctrl-r (for Vi mode check doc)
export HSTR_TIOCSTI=y

